export const FORM_VALIDATE = "FORM_VALIDATE";
export const FORM_VALIDATE_SUCCESS = "FORM_VALIDATE_SUCCESS";
export const FORM_VALIDATE_ERROR = "FORM_VALIDATE_ERROR";

export const START_API_FILM = "START_API_FILM";
export const API_FILM_SUCCESS = "API_FILM_SUCCESS";
export const API_FILM_ERROR = "API_FILM_ERROR";
