export const FORM_VALIDATE = "FORM_VALIDATE";
export const FORM_VALIDATE_SUCCESS = "FORM_VALIDATE_SUCCESS";
export const FORM_VALIDATE_ERROR = "FORM_VALIDATE_ERROR";

export const CLEAN_API_FILM = "CLEAN_API_FILM";
export const START_API_FILM = "START_API_FILM";
export const API_FILM_SUCCESS = "API_FILM_SUCCESS";
export const API_FILM_ERROR = "API_FILM_ERROR";
export const START_FILM_DETAILS = "START_FILM_DETAILS";
export const DETAILS_FILM_SUCCESS = "DETAILS_FILM_SUCCESS";
export const DETAILS_FILM_ERROR = "DETAILS_FILM_ERROR";
export const API_FILM_FULL = "API_FILM_FULL";
export const API_FILM_FULL_SUCCESS = "API_FILM_FULL_SUCCESS";
export const API_FILM_FULL_ERROR = "API_FILM_FULL_ERROR";
export const START_FILM_CHARACTER = "START_FILM_CHARACTER"
export const FILM_CHARACTER_SUCCESS = "FILM_CHARACTER_SUCCESS";
export const FILM_CHARACTER_ERROR = "FILM_CHARACTER_ERROR"

export const START_API_CHARACTER = "START_API_CHARACTER";
export const API_CHARACTER_SUCCESS = "API_CHARACTER_SUCCESS";
export const API_CHARACTER_ERROR = "API_CHARACTER_ERROR";
export const START_NAME_CHARACTER = "START_NAME_CHARACTER";
export const NAME_CHARACTER_SUCCESS = "NAME_CHARACTER_SUCCESS";
export const NAME_CHARACTER_ERROR = "NAME_CHARACTER_ERROR";
export const START_DETAILS_CHARACTER = "START_DETAILS_CHARACTER";
export const DETAILS_CHARACTER_SUCCESS = "DETAILS_CHARACTER_SUCCESS";
export const DETAILS_CHARACTER_ERROR = "DETAILS_CHARACTER_ERROR";

export const START_API_PHOTO = "START_API_PHOTO";
export const API_PHOTO_SUCCESS = "API_PHOTO_SUCCESS";
export const API_PHOTO_ERROR = "API_PHOTO_ERROR";
